Reorganized code and comments

diff --git a/evemenu b/evemenu
--- a/evemenu
+++ b/evemenu
@@ -5,54 +5,111 @@
 # Date:   01 Aug 2022
 # Brief:  Let the user launch anything via dmenu.
 #
-# Copyright (c) 2022 Marco Plaitano
+# Copyright (c) 2023 Marco Plaitano
 
 
 ##################################################
-#                 SCRIPT FUNCTIONS               #
+#                DMENU APPEARANCE                #
+##################################################
+
+font="monospace-12"
+
+# Background.
+nb="#262626"
+# Foreground.
+nf="#aaaaaa"
+# Selected item background.
+sb="#447375"
+# Selected item foreground.
+sf="#ffffff"
+
+
+
+##################################################
+#                    ACTIONS                     #
+##################################################
+
+_WEBBROWSER=${WEBBROWSER:=firefox}
+_CALCULATOR=${CALCULATOR:=mate-calc}
+
+# Key-Value pairs in which:
+# Key   = name of the action.
+# Value = command to perform.
+declare -A actions=(
+    [all]="_ask_dmenu -p run:"              # Launch regular instance of dmenu.
+    [amazon]="$_WEBBROWSER amazon.com"
+    [appearance]="xfce4-appearance-settings"
+    [calculator]="$CALCULATOR"
+    [code]="_choose_code_dir"
+    [discord]="discord"
+    [drive]="_choose_google_account drive.google.com/drive my-drive"
+    [firefox]="firefox"
+    [github]="$_WEBBROWSER github.com"
+    [instagram]="$_WEBBROWSER instagram.com"
+    [kill]="_choose_kill_process"
+    [lofi]="$_WEBBROWSER https://www.youtube.com/watch?v=jfKfPfyJRdk"
+    [logout]="xfce4-session-logout"
+    [mail]="_choose_google_account mail.google.com/mail \#inbox"
+    [mousepad]="mousepad"
+    [netflix]="$_WEBBROWSER netflix.com/browse"
+    [nightmode]="night_mode.sh --now"
+    [notion]="$_WEBBROWSER notion.so"
+    [poweroff]="poweroff"
+    [redshift]="redshift -x && redshift"
+    [screenshot]="xfce4-screenshooter"
+    [search]="_search_online"
+    [session]="xfce4-session-settings"
+    [settings]="xfce4-settings-manager"
+    [screenrecorder]="simplescreenrecorder"
+    [speedtest]="$_WEBBROWSER speedtest.net/run"
+    [spotify]="spotify"
+    [telegram]="Telegram"
+    [youtube]="$_WEBBROWSER youtube.com"
+    [whatsapp]="$_WEBBROWSER https://web.whatsapp.com"
+)
+
+
+
+##################################################
+#                    FUNCTIONS                   #
 ##################################################
 
 # Show error message and stop the execution of the script.
-function raise_error {
-    [[ -n $1 ]] && error_msg="$1" || error_msg="Error in 'evemenu'."
-
-    # Either echo the message if running the program in a terminal or display it
-    # as a notification.
-    if [[ -t 1 ]]; then
-        echo "$error_msg"
+_die() {
+    [[ -n $1 ]] && error_msg="$1" || error_msg="Error in $(basename "$0")."
+    if [[ $TERM != dumb ]]; then
+        echo "$error_msg" >&2
     else
-        notify-send "evemenu" "$error_msg"
+        notify-send "Error in $(basename "$0")" "$error_msg"
     fi
-
-    # Stop the execution of the program.
     exit 1
 }
 
-
 # Run dmenu with the given options and list of choices.
-function ask_dmenu {
+_ask_dmenu() {
+    local prompt list multiple_lines accept_all lines
     # Parse function's arguments.
     while [[ -n $1 ]]; do
         case "$1" in
             # Prompt to display.
             -p | --prompt)
-                local prompt="$2" ; shift ; shift ;;
+                prompt="$2" ; shift ; shift ;;
             # List of choices.
             -l | --list)
-                local list="$2" ; shift ; shift ;;
+                list="$2" ; shift ; shift ;;
             # Display each choice on a new line.
             --multiple-lines)
-                local multiple_lines=true ; shift ;;
+                multiple_lines=true ; shift ;;
             # Accept any user input, without presenting a list of choices.
             --accept-all)
-                local accept_all=true ; shift ;;
+                accept_all=true ; shift ;;
             # Discard any other argument.
             *)
                 shift ;;
         esac
     done
 
-    local lines=0
+    lines=0
     # If requested, calculate the number of lines in the list string.
     if [[ $multiple_lines == true ]]; then
         lines=$(echo -e "$list" | wc -l)
@@ -73,23 +130,24 @@ function ask_dmenu {
 
 
 ##################################################
-#                 ACTION FUNCTIONS               #
+#                    ROUTINES                    #
 ##################################################
 
 ### CALLED BY ACTION "code"
 # Choose a directory to open in a new VS Code window.
-function choose_editor_directory {
-    local dirs_string="default\nempty"
+_choose_code_dir() {
+    local dirs_string dir _CODE_ROOT_DIR
+    _CODE_ROOT_DIR="$HOME/Desktop"  # Were to look for projects to open.
 
     # Append all possible directories to one string.
-    # See below for declaration of CODE_DIR.
-    for dir in $(find "$CODE_DIR" -maxdepth 1 -type d); do
-        [[ "$dir" == "$CODE_DIR" ]] && continue
+    dirs_string="default\nempty"
+    for dir in $(find "$_CODE_ROOT_DIR" -maxdepth 1 -type d); do
+        [[ "$dir" == "$_CODE_ROOT_DIR" ]] && continue
         dirs_string+="\n"$(basename "$dir")
     done
 
     # Ask which directory to open.
-    local dir=$(ask_dmenu -p "directory:" -l "$dirs_string" --multiple-lines)
+    dir=$(_ask_dmenu -p "directory:" -l "$dirs_string" --multiple-lines)
     [[ -z $dir ]] && exit
 
     # Open an empty window.
@@ -98,139 +156,60 @@ function choose_editor_directory {
     # "default" will open a window with last active workspace.
     elif [[ "$dir" == "default" ]]; then
         code
-    elif [[ -d "$CODE_DIR"/"$dir" ]]; then
-        code "$CODE_DIR"/"$dir"
+    elif [[ -d "$_CODE_ROOT_DIR"/"$dir" ]]; then
+        code "$_CODE_ROOT_DIR"/"$dir"
     fi
 }
 
-
 ### CALLED BY ACTION "kill"
 # Choose a process to kill.
-function choose_kill_process {
-    local processes="firefox\nplank\nredshift"
-    # Ask for a process to kill. It can be any value, even one not listed in
-    # the 'processes' list above.
-    local process=$(ask_dmenu -p "which process?" -l $processes)
+_choose_kill_process() {
+    local processes process
+    # Ask for a process to kill. It can be any value, even one not listed here.
+    processes="firefox\nplank\nredshift\nspotify"
+    process=$(_ask_dmenu -p "which process?" -l $processes)
     killall "$process"
 }
 
-
 ### CALLED BY ACTIONS "drive", "mail"
 # Choose which account to open the given Google's site with.
-# When multiple accounts are active in the same browser, google will assign
-# a number to each one, going from 0 to ...
-# The first account the user uses to sign in is account n. 0, the second is
-# account n. 1 and so on.
-function choose_google_account {
-    local accounts="personal\nwork"
-    local account=$(ask_dmenu -p "which account?" -l $accounts)
+# When multiple accounts are active in the same browser, Google will assign
+# a number to each one, going from 0 to N-1
+_choose_google_account() {
+    local accounts account num
+    accounts="personal\nwork"
+    account=$(_ask_dmenu -p "which account?" -l $accounts)
+    [[ -z $account ]] && exit
     # Argument $1 is the site to open (either gmail, Drive, Photos, ...) and,
     # eventually, $2 is the specific page view in the site.
     case $account in
-        personal) $WEBBROWSER https://"$1"/u/0/"$2" ;;
-        work)     $WEBBROWSER https://"$1"/u/1/"$2" ;;
+        personal)  num=0 ;;
+        work)      num=1 ;;
     esac
+    $_WEBBROWSER "https://$1/u/$num/$2"
 }
 
-
 ### CALLED BY ACTION "search"
-# Ask what to search for online.
-function search_online {
-    local query=$(ask_dmenu -p "search for?" --accept-all)
+# Google something.
+_search_online() {
+    local query url domains
+    query=$(_ask_dmenu -p "search for?" --accept-all)
     [[ -z $query ]] && exit
     url="https://www.google.com/search?q=${query// /+}"
-    local domains=("com" "it" "gov" "en" "org")
+    domains=("com" "it" "gov" "en" "org")
     for domain in "${domains[@]}"; do
         if [[ $query == *.$domain ]]; then
             url="https://$query"
             break
         fi
     done
-    $WEBBROWSER "$url"
-}
-
-
-### CALLED BY ACTIONS "poweroff", "reboot"
-# Execute a series of commands before shutting down the machine.
-function shutdown_routine {
-    # ADD YOUR COMMANDS HERE. (e.g. killall firefox)
-    # . . .
-    # argument $1 is the command to execute, either 'poweroff' or 'restart'.
-    "$1"
+    $_WEBBROWSER "$url"
 }
 
 
 
 ##################################################
-#                DMENU APPEARANCE                #
-##################################################
-
-font="UbuntMono-12"
-
-# Background color.
-nb="#262626"
-# Foreground color.
-nf="#aaaaaa"
-# Selected item's background color.
-sb="#447375"
-# Selected item's foreground color.
-sf="#ffffff"
-
-
-
-##################################################
-#                    VARIABLES                   #
-##################################################
-
-# Root directory in which to look for directories containing coding projects.
-CODE_DIR=${CODE_DIR:=$HOME/Desktop}
-
-WEBBROWSER=${WEBBROWSER:=firefox}
-
-CALCULATOR=${CALCULATOR:=mate-calc}
-
-
-# Key-Value pairs in which:
-# Key   = name of the action.
-# Value = command to perform.
-declare -A actions=(
-    [all]="ask_dmenu -p run:" # Launch regular instance of dmenu.
-    [amazon]="$WEBBROWSER amazon.com"
-    [appearance]="xfce4-appearance-settings"
-    [calculator]="$CALCULATOR"
-    [code]="choose_editor_directory"
-    [discord]="discord"
-    [drive]="choose_google_account drive.google.com/drive my-drive"
-    [firefox]="firefox"
-    [github]="$WEBBROWSER github.com"
-    [instagram]="$WEBBROWSER instagram.com"
-    [kill]="choose_kill_process"
-    [lofi]="$WEBBROWSER https://www.youtube.com/watch?v=jfKfPfyJRdk"
-    [logout]="xfce4-session-logout"
-    [mail]="choose_google_account mail.google.com/mail \#inbox"
-    [mousepad]="mousepad"
-    [netflix]="$WEBBROWSER netflix.com/browse"
-    [nightmode]="night_mode.sh --now"
-    [notion]="$WEBBROWSER notion.so"
-    [poweroff]="shutdown_routine poweroff"
-    [reboot]="shutdown_routine reboot"
-    [redshift]="redshift -x && redshift"
-    [screenshot]="xfce4-screenshooter"
-    [search]="search_online"
-    [session]="xfce4-session-settings"
-    [settings]="xfce4-settings-manager"
-    [screenrecorder]="simplescreenrecorder"
-    [speedtest]="$WEBBROWSER speedtest.net/run"
-    [spotify]="spotify"
-    [telegram]="Telegram"
-    [youtube]="$WEBBROWSER youtube.com"
-    [whatsapp]="$WEBBROWSER https://web.whatsapp.com"
-)
-
-
-
-##################################################
-#                  MAIN SECTION                  #
+#                      MAIN                      #
 ##################################################
 
 # Sort the keys in alphabetical order and create one long string, separating
@@ -242,15 +221,13 @@ done
 # Remove last 2 characters (an exceeding \n).
 choices=${choices::-2}
 
-
 # The user chooses the action to perform via dmenu.
-selected=$(ask_dmenu -p "run:" -l "$choices")
+selected=$(_ask_dmenu -p "run:" -l "$choices")
 [[ -z $selected ]] && exit
-
 
 # Execute the chosen action.
 if [[ -v actions[$selected] ]]; then
     ${actions[$selected]} & exit
 else
-    raise_error "Action '$selected' not found."
+    _die "Action '$selected' not found."
 fi
